proxy:
  secretToken: "e6dfc88ad3de50d3f44f905595bbadaeeb3598ed9e8b1ba50a08787292965cd0"

prePuller:
  continuous:
    enabled: true

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
  userPods:
    nodeAffinity:
      matchNodePurpose: prefer

cull:
  enabled: true
  timeout: 600
  every: 150

singleuser:
  defaultUrl: "/lab"
  image:
    name: nycdsa/hadoop-notebook-spark
    tag: 0.3
  profileList:
    - display_name: "Hadoop environment"
      description: "Hadoop environment with Hive, Pig and Spark"
      default: true
  memory:
    limit: 4G
    guarantee: 1G
  cpu:
    limit: 2
    guarantee: 0.5
  storage:
    capacity: 4Gi

hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']

auth:
  type: dummy
  dummy:
    password: 'EchEt7JEHS'
  admin:
    access: true
    users:
      - aetnaJHubAdmin@k8s
  whitelist:
    users:
      - test
      - alex
      - justinfox
      - tmolnar
      - allenc3
      - conoverr
      - murphyr
      - siddiquit
      - murphyr
      - bommanlingaiahm
      - murphyr
      - mli01
      - robinsonam
      - quereshiw
      - gopalann1
      - lix4637
      - zhengb2
      - allenl7
      - sankars3
      - yes5284
