proxy:
  secretToken: "e6dfc88ad3de50d3f44f905595bbadaeeb3598ed9e8b1ba50a08787292965cd0"

prePuller:
  continuous:
    enabled: true

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
  userPods:
    nodeAffinity:
      matchNodePurpose: prefer

cull:
  enabled: true
  timeout: 600
  every: 150

singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/minimal-notebook
    tag: 83ed2c63671f
  profileList:
    - display_name: "Base environment"
      description: "Ubuntu 18.04 with Jupyter Notebook"
      default: true
    - display_name: "Spark environment"
      description: "Jupyter Notebook Python, Spark, Mesos Stack"
      kubespawner_override:
        image: jupyter/pyspark-notebook:83ed2c63671f
    - display_name: "Hadoop base"
      kubespawner_override:
        image: nycdsa/hadoop-notebook:0.1

  memory:
    limit: 4G
    guarantee: 1G
  cpu:
    limit: 2
    guarantee: 0.5
  storage:
    capacity: 4Gi
    # extraVolumes:
    #   - name: jhub-shared
    #     persistentVolumeClaim:
    #       claimName: pv-claim-cloudlab
    # extraVolumeMounts:
    #   - name: jhub-shared
    #     mountPath: /mnt/data
    #     readOnly: true

hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']

auth:
  type: dummy
  dummy:
    password: 'nycdsa_jhub'
  admin:
    access: true
    users:
      - aetna_admin
  whitelist:
    users:
      - shuyan
      - chrisneimeth
      - lukelin
      - zeyuzhang
      - aikoliu
      - xunwang
      - royceho
      - vivianzhang
      - dracezhang
      - alexbaransky
      - justinfox

