proxy:
  secretToken: "e6dfc88ad3de50d3f44f905595bbadaeeb3598ed9e8b1ba50a08787292965cd0"

singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/r-notebook
    tag: a238993ad594

hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']

auth:
  type: dummy
  dummy:
    password: 'testpswd'
  admin:
    access: true
    users:
      - admin_user
  whitelist:
    users:
      - shuyan
      - tester
